default_language_version:
  python: python3.8
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v3.2.0"
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/PyCQA/flake8
  rev: "3.9.0"
  hooks:
  - id: flake8
    additional_dependencies:
    - "flake8-quotes"
    args:
    - --config=./setup.cfg
    exclude: ".*template.*"
- repo: https://github.com/PyCQA/isort
  rev: "5.8.0"
  hooks:
  - id: isort
    name: isort
    exclude: ".*template.*"
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.812"
  hooks:
  - id: mypy
    args:
    - --follow-imports=silent
    - --ignore-missing-imports
    - --show-column-numbers
    - --show-error-codes
    - --warn-no-return
    - --warn-unreachable
    - --warn-unused-ignores
    exclude: ".*template.*"
- repo: local
  hooks:
  - id: pipenv-clean
    name: pipenv-clean
    description: Makes sure local environment matches committed Pipfile*
    entry: pipenv clean
    language: system
    files: 'Pipfile*'
    pass_filenames: false
  - id: pipenv-check
    name: pipenv-check
    description: Makes sure new/current dependencies don't have security vulnerabilities
    entry: pipenv check --quiet
    language: system
    files: 'Pipfile*'
    always_run: true
    pass_filenames: false
